discountdata:
  discountMap:
    FURNISHING: 10.00
    KITCHENELECTRONIC: 20.00
    MOBILEPHONE: 5.00
    TOY: 2.00
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    
server:
  port: 8083
  
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
      
spring:
  application:
    name: discount-service
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
    trace-id128: true
  zipkin:
    base-url: ${zipkin.url:http://192.168.99.102:9411}
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'health'  server:    port: 8084