spring:
  application:
    name: audit-store
  rabbitmq:
    host: 192.168.99.102
    password: guest
    port: 5672
    username: guest
  cloud:
    stream:
      bindings:
        input:
          destination: auditinfo
          group: productgroup            
      default:
        contentType: application/json
        
server:  port: 8086